---
- hosts: all
  remote_user: "{{ remote_user }}"
  roles:
    - { role: cuckoo, when: "ansible_version.full | version_compare('1.8', '>=')" }
    - { role: yara  , when: "{{ install_yara   }}" }
    - { role: ssdeep, when: "{{ install_ssdeep }}" }
    - { role: volatility, when: "{{ install_volatility }}" }
