---

  - name: install dependancies using apt
    apt:
      name  : "{{ item }}"
      state : "present"
    sudo: yes
    with_items:
      - python
      - python-pip
      - mongodb
      - qemu-kvm
      - libvirt-bin
      - python-libvirt
      - bridge-utils
      - tcpdump
      - libcap2-bin
      - virt-manager
      - qemu-system
      - ubuntu-vm-builder

  - name: install dependancies using pip (1 of 2)
    pip:
      name  : "{{ item }}"
      state : "present"
    sudo: yes
    with_items:
      - dpkt
      - nose
      - jinja2
      - bottle
      - pefile
      - django
      - pymongo
      - chardet
      - sqlalchemy
      - python-magic

  - name: install dependancies using pip (2 of 2)
    pip:
      name    : "{{ item.name }}"
      version : "{{ item.version }}"
    sudo: yes
    with_items:
      - { name: "cybox", version: "2.1.0.9"  }
      - { name: "maec" , version: "4.1.0.11" }

  - name: find path to the tcpdump binary
    command      : "which tcpdump"
    register     : path_tcpdump
    changed_when : False

  - name: set capabilities on tcpdump
    capabilities:
      path       : "{{ path_tcpdump.stdout }}"
      capability : "cap_net_raw,cap_net_admin=eip"
      state      : "present"
    sudo: yes
